### PR TITLE
Use async methods and return a Promise

### PR DESCRIPTION
**Pull request by sparksp**
This is recommended by [postcss when writing plugins][postcss-guide].

Adds [make-dir] which creates directories and parents if needed (like `mkdir -p`) and plays well with promises / async.

Based on and closes #17.

Co-authored-by: [yonigibbs]

[make-dir]: https://www.npmjs.com/package/make-dir
[postcss-guide]: https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#22-use-asynchronous-methods-whenever-possible
[yonigibbs]: https://github.com/yonigibbs

### CODE REVIEW

**Comment by sparksp** [comment]
The weird thing with this is that when I use the package locally (yarn link'd) it works fine, but when I try to use the package as a git source then something silently errors and prevents tailwind from processing.

**Comment by yonigibbs** [comment]
@sparksp, that's very generous of you to mention me as a co-author of this. You definitely did the lion's share of the work in this PR :-)

Anyway, just to say, if you want me to try something out locally to see if we can get to the bottom of the weirdness you're seeing when using a git source, don't hesitate to ask.

**Comment by sparksp** [comment]
@yonigibbs I wanted to recognise that you'd started this work - I probably wouldn't have even realised it was needed otherwise.  It would be great if you can give it a try from the git source and see that it works for you. I'm hanging out on slack today @sparksp if you want to give me a shout.

**Comment by sparksp** [comment]
It turns out that I added [make-dir] as a devDependency by mistake - moving this to `dependencies` seems to have solved the problem!

It does highlight a problem with the demo check, since yarn's already been run on the main project directory all the dev dependencies are available.

**Comment by yonigibbs** [comment]
I was hoping the changes here would resolve the problem with intermittent failures when using Parcel (caused by a race condition, it seems), but unfortunately it seems not. If I simulate a long file-write operation by adding a sleep in `writeFile`, the operation fails. To make this more robust I think we'll need to find a way to tell Parcel that the Elm code generation depends on the postcss step, or get it all to run in serial.

**Comment by sparksp** [comment]
@monty5811 this is good to go now - there's only the outstanding question of whether we _should_ log to the console or not, left in because that's what you were doing before.

I've also fixed the demo build job so that it will properly notice if there's any missing dependencies now.

**Pull request merged**
