### PR TITLE
Upgrade postcss to 8.0.0 Upgrade tailwindcss, @tailwindcss-form

### PR DESCRIPTION
**Pull request by jangerhard**

### CODE REVIEW

**Comment by jangerhard** [comment]
Tailwind 2.0 adds a new `2XL` breakpoint, which breaks the elm file-creation as filenames cannot start with a number; `2XL.elm` is invalid.

**Comment by monty5811** [comment]
> @monty5811 What do you think over changing screen-names that start with a number to an appended version:
> `2XL.elm` -> `XL_2.elm`
> 
> I'm not really a fan, but I cannot really think of a better solution..

Yeah, what about `TwoXL`? What do you think?

**Comment by jangerhard** [comment]
https://github.com/tailwindlabs/tailwindcss/issues/3069

GHNewbiee suggested `2XL` -> `XXL` and I kinda like it! 

There's also an issue mentioned here where `\3` is used to escape classes that start with a number. It shows up in the generated classes in the elm-file, but I have yet to write a test that breaks.

**Comment by jangerhard** [comment]
The previous commit results in clean Elm-code: 
```
tw_rounded_md : Html.Attribute msg
tw_rounded_md =
    A.class "\\32xl:tw-rounded-md"


tw_rounded_lg : Html.Attribute msg
tw_rounded_lg =
    A.class "\\32xl:tw-rounded-lg"


tw_rounded_xl : Html.Attribute msg
tw_rounded_xl =
    A.class "\\32xl:tw-rounded-xl"
```

However, it does not seem like the actual css-property is included in the final, compiled css-file.

**Comment by jangerhard** [comment]
Do you think this is ready, @monty5811 ? Tests are running and I've updated so that the examples are still valid. The 2XL screen-size, or any other sizes that start with a number, now produce valid elm-classes.

**Comment by monty5811** [comment]
Yes, this looks great! Thank you for all the work on this!!

**Review by monty5811 — APPROVED** [review]
Fantastic!

**Comment by jangerhard** [comment]
@monty5811 Are you pushing a new version? :)

**Pull request merged**
